# Pull gems from RubyGems
source 'https://rubygems.org'

# ~> Refers to all versions of the given gem on the current full version number, so it will be able to use any version of Compass Aurora until Compass Aurora 4.x.x. For a specific version of a gem, remove the ~>

# This is the gem containing all of the dependencies required for Style Prototypes
gem 'style-prototypes', '~>1.0'

# This is your Compass extension. Update it's name and version number accordingly.
gem 'styleguide',       '~>1.0'


# Now that you're using Bundler, you need to run `bundle exec compass watch` instead of simply `compass watch`.